[target.armv7-linux-androideabi]
linker = "arm-linux-androideabi-clang"
ar = "arm-linux-androideabi-ar"
rustflags = [
    "-C",
    "link-arg=-lc++_static",
    "-C",
    "link-arg=-lc++abi",
    "-C",
    "link-arg=-landroid_support"
]
