# `cargo install cargo-about`
# `cargo about generate about.hbs > licenses.html`
accepted = [
    "GPL-3.0",
    "MPL-2.0",
    "MIT",
    "ISC",
    "Apache-2.0",
    "0BSD",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "CC0-1.0",
    "Unicode-DFS-2016",
    "BSL-1.0",
    "OpenSSL",
    "OpenSSL-standalone",
    "SSLeay-standalone",
    "NOASSERTION",
]
