mod battle_init_scene;
mod battle_scene;
mod battle_select_scene;
mod blocks_scene;
mod boot_scene;
mod character_scene;
mod character_select_scene;
mod config_scene;
mod credits_scene;
mod deck_editor_scene;
mod deck_list_scene;
mod initial_connect_scene;
mod key_item_scene;
mod library_scene;
mod main_menu_scene;
mod manage_switch_drive_scene;
mod netplay_init_scene;
mod overworld_online_scene;
mod package_scene;
mod package_updates_scene;
mod packages_scene;
mod resource_order_scene;
mod server_edit_scene;
mod server_list_scene;
mod sync_data_scene;

pub use battle_init_scene::*;
pub use battle_scene::*;
pub use battle_select_scene::*;
pub use blocks_scene::*;
pub use boot_scene::*;
pub use character_scene::*;
pub use character_select_scene::*;
pub use config_scene::*;
pub use credits_scene::*;
pub use deck_editor_scene::*;
pub use deck_list_scene::*;
pub use initial_connect_scene::*;
pub use key_item_scene::*;
pub use library_scene::*;
pub use main_menu_scene::*;
pub use manage_switch_drive_scene::*;
pub use netplay_init_scene::*;
pub use overworld_online_scene::*;
pub use package_scene::*;
pub use package_updates_scene::*;
pub use packages_scene::*;
pub use resource_order_scene::*;
pub use server_edit_scene::*;
pub use server_list_scene::*;
pub use sync_data_scene::*;

#[cfg(debug_assertions)]
mod font_test_scene;
#[cfg(debug_assertions)]
pub use font_test_scene::*;
