local json = require("scripts/libs/json")

---Arbitrary data storage using string keys. Anything that can be encoded as json can be stored.
local DataStorage = {
  PATH = "./data_storage"
}

local _loaded = {}
local _pending_write = {}

---Ensures DataStorage.PATH exists, this should be called in a single file at server start.
function DataStorage.init()
  return Async.ensure_dir(DataStorage.PATH)
end

---Asynchronously loads saved data using the provided key, this data will be cached for future calls until `unload` is called.
---A default value can be generated by passing a function as the second argument.
---@param key string
---@param create_default? fun(): any
---@return Net.Promise<any>
function DataStorage.load(key, create_default)
  return Async.create_scope(function()
    local value = _loaded[key]

    if value ~= nil then
      return value
    end

    local content = Async.await(Async.read_file(DataStorage.get_path(key)))

    -- see if load_sync or another load was called before we could finish loading
    value = _loaded[key]

    if value then
      return value
    end

    if content == "" then
      if create_default then
        value = create_default()
      end
    else
      value = json.decode(content)
    end

    _loaded[key] = value
    return value
  end)
end

---Synchronously loads saved data using the provided key, this data will be cached for future calls until `unload` is called.
---A default value can be generated by passing a function as the second argument.
---@param key string
---@param create_default? fun(): any
---@return any
function DataStorage.load_sync(key, create_default)
  local value = _loaded[key]

  if value then
    return value
  end

  local file = io.open(DataStorage.get_path(key), "r")

  if not file then
    if create_default then
      value = create_default()
    end
  else
    value = json.decode(file:read("a"))
    file:close()
  end

  _loaded[key] = value
  return value
end

---Unloads data from cache, requiring the relevant file to be read on the next call to a load function.
---@param key string
function DataStorage.unload(key)
  _loaded[key] = nil
end

---Immediately caches the new value, then asynchronously writes the value to a file.
---@param key string
---@param value any
function DataStorage.store(key, value)
  if value == nil then
    return
  end

  _loaded[key] = value

  local pending_write = _pending_write[key]

  local next_write = function()
    _pending_write[key] = Async.create_scope(function()
      Async.await(Async.write_file(DataStorage.get_path(key), json.encode(value)))
      _pending_write[key] = nil
      return nil
    end)
  end

  if pending_write then
    pending_write.and_then(next_write)
  else
    next_write()
  end
end

---@param key string
function DataStorage.get_path(key)
  return DataStorage.PATH .. "/" .. Net.encode_uri_component(key) .. ".json"
end

return DataStorage
