local Emotes = {
  BIG_SMILE = "BIG SMILE",
  CRY_LAUGHING = "CRY LAUGHING",
  SMILE = "SMILE",
  SHOCKED = "SHOCKED",
  COOL = "SUNGLASSES",
  PLEADING = "PLEADING",
  MIND_BLOWN = "EXPLODING HEAD MIND BLOWN",
  EXPRESSIONLESS = "EXPRESSIONLESS",
  PENSIVE = "PENSIVE",
  CRYING = "CRYING SOBBING",
  UNCOOL = "CRYING SUNGLASSES",
  VOMIT = "PUKING VOMITING",

  PVP = "PVP SWORDS BATTLE",
  GG = "GG",
  COB = "CORN COB POG",
  WAVE = "WAVE HELLO GOODBYE",
  THUMBS_UP = "THUMBS UP",
  THUMBS_DOWN = "THUMBS DOWN",
  ANGRY = "ANGRY RAGE",
  EVIL_GRIN = "EVIL GRIN SMILING IMP",
  CLOWN = "CLOWN",
  RAINBOW_CLOWN = "RAINBOW CLOWN",
  QUESTION = "QUESTION MARK?",
  ALERT = "EXCLAMATION MARK!",
  ZZZ = "SLEEPING ZZZ AFK",

  CHIP = "CHIP",
  HEART = "LOVE HEART",
}

-- backwards compat
Emotes.HAPPY = Emotes.BIG_SMILE
Emotes.BLANK = Emotes.EXPRESSIONLESS
Emotes.MAD = Emotes.ANGRY
Emotes.SAD = Emotes.CRYING
Emotes.KEY = ""
Emotes.LOL = Emotes.CRY_LAUGHING
Emotes.YES = Emotes.THUMBS_UP
Emotes.NO = Emotes.THUMBS_DOWN
Emotes.SPIRIT = Emotes.EVIL_GRIN

return Emotes
