local Emotes = {
  HAPPY = "BIG SMILE",
  BLANK = "EXPRESSIONLESS",
  MAD = "ANGRY",
  SAD = "CRYING SOBBING",
  SMUG = "SMILE",
  SHOCKED = "SHOCKED",
  COB = "EXPLODING HEAD",
  PVP = "PVP SWORDS",
  ZZZ = "SLEEPING ZZZ",
  KEY = "",
  QUESTION = "QUESTION MARK!",
  ALERT = "EXCLAMATION MARK!",
  HEART = "LOVE HEART",
  GG = "",
  LOL = "CRY LAUGHING",
  YES = "THUMBS UP",
  NO = "THUMBS DOWN",
  VOMIT = "PUKING VOMITING",
  COOL = "SUNGLASSES",
  UNCOOL = "CRYING SUNGLASSES",
  SPIRIT = "EVIL GRIN SMILING IMP",
  CLOWN = "CLOWN",
  PENSIVE = "PENSIVE",
  PLEADING = "PLEADING",
  MIND_BLOWN = "EXPLODING HEAD MIND BLOWN"
}

return Emotes
