#pragma once
#include <string>

#define MAKE_ID(name, uuid) static const std::string name = #uuid
#define MAKE_ID_LIST(...) const std::initializer_list<std::string> AsList { __VA_ARGS__ };

// We need cards that will be represented by the web api
// Here we can create UUID strings to use for in-game rewards
// NOTE: if you have your own Web API server, you need
//       to use the new UUIDs generated by the web api
namespace BuiltInCards {
    MAKE_ID(Cannon, 5e00025204648c1e215f3a6b);
    MAKE_ID(Reflect, 5e126ef61cd1b708dd08d7f4);
    MAKE_ID_LIST(Cannon, Reflect);
}

#undef MAKE_ID
#undef MAKE_ID_LIST