.PHONY: clean All

All:
	@echo "----------Building project:[ BattleNetwork - Debug ]----------"
	@"$(MAKE)" -f  "BattleNetwork.mk"
clean:
	@echo "----------Cleaning project:[ BattleNetwork - Debug ]----------"
	@"$(MAKE)" -f  "BattleNetwork.mk" clean
