name: Android Test

on:
  push:
    branches:
      - master

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Target SDK
        run: sdkmanager --install "platforms;android-30" "platforms;android-35" ndk-bundle

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Install Linker
        run: |
          sudo apt-get update
          sudo apt-get install -y mold
          mkdir .cargo
          printf "[target.x86_64-unknown-linux-gnu]\nlinker = \"/usr/bin/clang\"\nrustflags = [\"-C\", \"link-arg=--ld-path=/usr/bin/mold\"]" > .cargo/config.toml

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: android-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: android-cargo

      - name: Install Cargo APK Dependencies
        run: |
          rustup target add armv7-linux-androideabi aarch64-linux-android
          cargo install cargo-apk

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > client/release.keystore

      - name: Build APK
        run: cargo run --bin dist-android

      # - name: Push to itch.io
      #   run: |
      #     mkdir butler
      #     cd butler
      #     wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
      #     unzip butler.zip
      #     chmod +x ./butler
      #     export BUTLER_API_KEY=${{ secrets.BUTLER_API_KEY }}
      #     ./butler push ../dist/hub_os.apk hub-os/hub-os:android --userversion 0.62.0
      #     cd ..
