name: Automated Builds

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Real PET
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - name: Install Cargo About
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-about

      - name: MinGW Setup
        uses: egor-tensin/setup-mingw@v2
        with:
          cc: 0

      - name: Build Windows Client
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --bin real_pet
            --release
            --target
            x86_64-pc-windows-gnu

      - name: Build Windows Server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --bin real_pet_server
            --release
            --target
            x86_64-pc-windows-gnu

      - name: Build Linux Executables and Create Dist
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: |
            --bin
            dist

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
