name: Automated Builds

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Real PET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - name: Build Windows
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --release
            --target
            x86_64-pc-windows-gnu

      - name: Build Linux and Create Dist
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: |
            --bin
            --target
            dist

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
