name: Automated Builds

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Real PET
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            target/
          key: ${{ runner.os }}-cargo

      - name: Install Cargo About
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-about
          version: "0.5"

      - name: MinGW Setup
        uses: egor-tensin/setup-mingw@v2
        with:
          cc: 0

      - name: Make Release Folder
        run: mkdir -p target/release

      - name: Build Windows Client
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --bin
            real_pet
            --release
            --target
            x86_64-pc-windows-gnu

      - name: Build Windows Server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --bin
            real_pet_server
            --release
            --target
            x86_64-pc-windows-gnu

      - name: Copy Windows Executables
        run: |
          cp target/x86_64-pc-windows-gnu/release/real_pet.exe target/release/real_pet.exe
          cp target/x86_64-pc-windows-gnu/release/real_pet_server.exe target/release/real_pet_server.exe

      - name: Install Linux Dependencies
        run: sudo apt install -y libasound2-dev libudev-dev libxcb-xfixes0-dev libxcb-shape0-dev

      - name: Build Linux Executables and Create Dist
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: |
            --bin
            dist

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
